apiVersion: v1
kind: Service
metadata:
  name: seldon-lb-svc
  namespace: istio-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http2-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
