apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mnist-prod
spec:
  name: mnist-prod
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          image: jear/seldon-mnist:1.3.4
    graph:
      children: []
      parameters:
        - name: det_master
          type: STRING
          value: "192.168.201.75"
        - name: model_name
          type: STRING
          value: "MNISTModel"
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: mnist-prod
    replicas: 1
